EXPERIMENT_NAME: 'eval-baseline-80m-nuscenes-val'

SYSTEM:
  BENCHMARK: False

LOAD:
  # CHECKPOINT_PATH: 'log/checkpoints/clear_teacher_nuscenes.ckpt'
  CHECKPOINT_PATH: 'log/checkpoints/train-unc-distll-dd/train-unc-distll-dd-epoch=04.ckpt'
  DAYTIME_TRANSLATION_TEACHER_PATH: 'log/checkpoints/clear_teacher_nuscenes.ckpt'
  # DAYTIME_TRANSLATION_TEACHER_PATH: 'log/checkpoints/clear_teacher_nuscenes.ckpt'

DATASET:
  DATAROOT: '../nuscenes'
  # VERSION: 'mini'

EVALUATION:
  BATCH_SIZE: 1
  SAVE:
    QUANTITATIVE_RES_PATH: 'results/quantitative/nuscenes/val'

TRAINING:
  BATCH_SIZE: 16
  SELF_DISTILL: True

LOSS:
  SUPERVISED:
    WEIGHT: 1.0
    METHOD: 'unc_sim'
